# Generated by Django 6.0 on 2025-12-25 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 25, 16, 23, 40, 104423, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
