# Generated by Django 6.0 on 2025-12-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_companyinfo_companysociallink_banner_tagline_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.DeleteModel(
            name='CompanySocialLink',
        ),
    ]
