# Generated by Django 6.0 on 2026-01-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_payment_id_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('culqi', 'Culqi'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
