# Generated by Django 6.0 on 2026-01-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
