# Generated by Codex on 2026-06-04

from django.db import migrations, models
from django.utils import timezone


def copy_created_at_to_updated_at(apps, schema_editor):
    Cart = apps.get_model("app", "Cart")
    CartItem = apps.get_model("app", "CartItem")

    for cart in Cart.objects.all().only("id", "created_at"):
        Cart.objects.filter(id=cart.id).update(
            updated_at=cart.created_at or timezone.now()
        )

    for item in CartItem.objects.all().only("id", "created_at"):
        CartItem.objects.filter(id=item.id).update(
            updated_at=item.created_at or timezone.now()
        )


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_user_google_sub"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(copy_created_at_to_updated_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
